CREATE TABLE [dbo].[Activity]
(
	[ActivityId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
	[UserId] UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(255) NULL, 
    [ImageURL] NVARCHAR(255) NULL,
	[Active] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [FK_Activity_User] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId]), 
	CONSTRAINT [PK_Activity] PRIMARY KEY ([ActivityId])
	
)
