CREATE TABLE [dbo].[Field]
(
	[FieldId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[UserId] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(50) NOT NULL, 
    [AllowFreeText] BIT NOT NULL DEFAULT 1
    CONSTRAINT [FK_Field_User] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId]), 
)
